use std::path::PathBuf;
use std::time::SystemTime;

/// Where a session originated from.
#[derive(Debug, Clone)]
pub enum SessionSource {
    /// Local session from ~/.claude/projects
    Local,
    /// Remote session synced via SSH
    Remote {
        /// Config key (e.g., "devbox")
        name: String,
        /// SSH alias or raw hostname/IP
        host: String,
        /// Only needed for raw hosts without SSH config
        user: Option<String>,
    },
}

impl SessionSource {
    /// Display name for the source (e.g., "local", "devbox")
    pub fn display_name(&self) -> &str {
        match self {
            SessionSource::Local => "local",
            SessionSource::Remote { name, .. } => name,
        }
    }

    #[cfg(test)]
    pub fn is_local(&self) -> bool {
        matches!(self, SessionSource::Local)
    }
}

#[derive(Debug)]
pub struct Session {
    pub id: String,
    pub project: String,
    pub project_path: String,
    pub filepath: PathBuf,
    pub created: SystemTime,
    pub modified: SystemTime,
    pub first_message: Option<String>,
    pub summary: Option<String>, // Session summary generated by Claude
    pub name: Option<String>,    // customTitle from /rename - indicates important session
    pub tag: Option<String>,     // searchable label from /tag
    pub turn_count: usize,       // Number of user messages (conversation turns)
    pub source: SessionSource,   // Where this session came from
    pub forked_from: Option<String>, // Parent session ID if this is a fork
}
