use std::path::PathBuf;
use std::time::SystemTime;

/// Which assistant CLI produced a session.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SessionAgent {
    Claude,
    Codex,
}

impl SessionAgent {
    pub fn display_name(self) -> &'static str {
        match self {
            SessionAgent::Claude => "claude",
            SessionAgent::Codex => "codex",
        }
    }

    pub fn storage_dir(self) -> &'static str {
        self.display_name()
    }
}

/// Where the transcript file currently lives.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SessionStorage {
    Live,
    Archive,
    Trash,
}

impl SessionStorage {
    pub fn display_name(self) -> &'static str {
        match self {
            SessionStorage::Live => "live",
            SessionStorage::Archive => "archive",
            SessionStorage::Trash => "trash",
        }
    }

    pub fn is_live(self) -> bool {
        matches!(self, SessionStorage::Live)
    }
}

/// Where a session originated from.
#[derive(Debug, Clone)]
pub enum SessionSource {
    /// Local session from ~/.claude/projects
    Local,
    /// Session from a cc-multiplexor profile (its own CLAUDE_CONFIG_DIR under
    /// ~/.claude-profiles/<name>). Resumed with that config dir so the session
    /// reopens under the right account.
    Profile {
        /// Profile name (e.g., "work", "personal")
        name: String,
        /// The profile's CLAUDE_CONFIG_DIR
        config_dir: PathBuf,
    },
    /// Remote session synced via SSH
    Remote {
        /// Config key (e.g., "devbox")
        name: String,
        /// SSH alias or raw hostname/IP
        host: String,
        /// Only needed for raw hosts without SSH config
        user: Option<String>,
    },
}

impl SessionSource {
    /// Display name for the source (e.g., "local", "devbox")
    pub fn display_name(&self) -> &str {
        match self {
            SessionSource::Local => "local",
            SessionSource::Profile { name, .. } => name,
            SessionSource::Remote { name, .. } => name,
        }
    }

    #[cfg(test)]
    pub fn is_local(&self) -> bool {
        matches!(self, SessionSource::Local)
    }
}

#[derive(Debug, Clone)]
pub struct Session {
    pub id: String,
    pub agent: SessionAgent,
    pub project: String,
    pub project_path: String,
    pub filepath: PathBuf,
    pub created: SystemTime,
    pub modified: SystemTime,
    pub first_message: Option<String>,
    pub summary: Option<String>, // Session summary generated by Claude
    pub name: Option<String>,    // customTitle from /rename - indicates important session
    pub tag: Option<String>,     // searchable label from /tag
    pub turn_count: usize,       // Number of user messages (conversation turns)
    pub source: SessionSource,   // Where this session came from
    pub storage: SessionStorage, // Live transcript, archived copy, or trash
    pub forked_from: Option<String>, // Parent session ID if this is a fork
}
